/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bank.ConnectionManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * GAD kalu worked on this
 */
public class Home extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs;
    public int accno;
    
    public Home(int acc) {
        initComponents();
        this.accno = acc;
        con = ConnectionManager.connect();
        getDataValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAccNo = new javax.swing.JLabel();
        btnWithdraw = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        txtEnteredAmount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Welcome");

        lblAccNo.setText("account_number");

        btnWithdraw.setBackground(new java.awt.Color(0, 204, 204));
        btnWithdraw.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnWithdraw.setText("Withdraw Money");
        btnWithdraw.setEnabled(false);
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnDeposit.setBackground(new java.awt.Color(0, 204, 102));
        btnDeposit.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnDeposit.setText("Deposit Money");
        btnDeposit.setEnabled(false);
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        jLabel2.setText("Name : ");

        jLabel3.setText("Account : ");

        jLabel4.setText("Balance : ");

        lblName.setText("jLabel5");

        lblAccountType.setText("jLabel5");

        lblBalance.setText("jLabel5");

        txtEnteredAmount.setBackground(new java.awt.Color(0, 102, 102));
        txtEnteredAmount.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtEnteredAmount.setForeground(new java.awt.Color(255, 255, 255));
        txtEnteredAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEnteredAmount.setText("0.00");
        txtEnteredAmount.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtEnteredAmountComponentAdded(evt);
            }
        });
        txtEnteredAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEnteredAmountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAccNo)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(124, 124, 124))))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(lblAccountType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEnteredAmount)
                            .addComponent(btnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAccNo)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(txtEnteredAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnWithdraw)
                .addGap(18, 18, 18)
                .addComponent(btnDeposit)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblAccountType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblBalance))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnteredAmountComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtEnteredAmountComponentAdded
        btnWithdraw.enable();
        btnDeposit.enable();
    }//GEN-LAST:event_txtEnteredAmountComponentAdded

    private void txtEnteredAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEnteredAmountMouseClicked
        btnWithdraw.setEnabled(true);
        btnDeposit.setEnabled(true);
    }//GEN-LAST:event_txtEnteredAmountMouseClicked

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        double amount = Double.parseDouble(txtEnteredAmount.getText());
        double balance = Double.parseDouble(lblBalance.getText());
        if(amount<=balance){
            //reduce the balance by amount
            double newBalance = balance-=amount;
            String query = "UPDATE user SET balance='"+newBalance+"' WHERE account_number='"+accno+"'";
        
        try {
            pst = con.prepareStatement(query);
            pst.execute();
            
            //clearTextBoxes();
            txtEnteredAmount.setText("");
            
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Balance Updated Successfully");
            lblBalance.setText(Double.toString(newBalance));
        } catch (SQLException ex) {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, ex);
        }
        }else{
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Balance is less than amount");
        }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        double amount = Double.parseDouble(txtEnteredAmount.getText());
        double balance = Double.parseDouble(lblBalance.getText());
        double newBalance = balance+=amount;
            String query = "UPDATE user SET balance='"+newBalance+"' WHERE account_number='"+accno+"'";
        
        try {
            pst = con.prepareStatement(query);
            pst.execute();
            
            //clearTextBoxes();
            txtEnteredAmount.setText("");
            
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Balance Updated Successfully");
            lblBalance.setText(Double.toString(newBalance));
        } catch (SQLException ex) {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, ex);
        }
    }//GEN-LAST:event_btnDepositActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtEnteredAmount;
    // End of variables declaration//GEN-END:variables

    private void getDataValues() {
        String query = "SELECT name, account, balance FROM user WHERE account_number = '"+accno+"'";
        try{
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            //tblEmployees.setModel(DbUtils.resultSetToTableModel(rs));
                if (rs.next()) {  
                String s = rs.getString(1);  
                String s1 = rs.getString(2);  
                String s2 = rs.getString(3);  
                //String s3 = rs.getString(4);  
                //Sets Records in TextFields.
                
                lblAccNo.setText(Integer.toString(accno));  
                lblName.setText(s);  
                lblAccountType.setText(s1);  
                lblBalance.setText(s2);  
            } else {  
                JOptionPane.showMessageDialog(null, "Name not Found");  
            }
        }
        catch(SQLException e){
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, e);
        }
       }
}
